version: '3'

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: pguser
      POSTGRES_DB: symfony
    volumes:
      - ../src/var/postgres/:/var/lib/postgresql/data
    ports:
      - 15432:5432

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ../src:/var/www/app

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


